### ISSUE TITLE
MockMP plugin with Gradle 7.2 gives error on multiplatform project

### ISSUE THREAD

**Issue by anar110** [Kodein-Framework/MocKMP#24]
On sync, I get the error:

```
Caused by: org.gradle.api.UnknownTaskException: Task with name 'kspDebugUnitTestKotlinAndroid' not found in project ':MobileShared'.
	at org.kodein.mock.gradle.MocKMPGradlePlugin$apply$1$4.execute(MocKMPGradlePlugin.kt:67)
        at org.kodein.mock.gradle.MocKMPGradlePlugin$apply$1$4.execute(MocKMPGradlePlugin.kt:11)
```

Taking out the plugin declaration, the sync goes through.
```
//id("org.kodein.mock.mockmp") version Versions.mockmp
```

MockMP version is 1.6.1

**Comment by SalomonBrys** [comment]
Can you share a reproducer project ?

I don't think this is linked to Gradle 7.2. It looks like the MocKMP plugin sees the Android plugin active, so it tries to integrates itself into the Android build workflow, but cannot find the required build task.
